### ISSUE TITLE
adding point to shape and saving not working well

### ISSUE THREAD

**Issue by ossarotte** [GeospatialPython/pyshp#105]
I edit a test shape whit this code
```
e = shapefile.Editor(shapefile="provashp2.shp")
e.point(10.81630981457014, 46.10253015644125,0,0)
e.record(3,"prova3",23,"prova da p")
e.save('provashp3')
```
the coordinates of poit is taken from this code

```
sf = shapefile.Reader("provashp1.dbf")
shapes = sf.shapes()
print shapes[0].points
```
that return 
[[10.81630981457014, 46.10253015644125]]
But when I open the new saved file this does not coincide with the startup,since the points are positioned on the other side and when I open with qgis ask the coordinate system to use 
the startup file is in etrs89 / utm zone 32N and i select the same for the new
What coordinates do I have to include?

**Comment by karimbahgat** [comment]
Closing since the Editor was discontinued a while back now.
