### ISSUE TITLE
Reader fails if file extension is uppercase

### ISSUE THREAD

**Issue by erickskb** [GeospatialPython/pyshp#117]
I ran into an issue where I receive a shapefile from an external system where the filename and extension is all uppercase. (/SHAPEFILE.SHP) the load function in the Reader class failed to read the file, because it is appending .shp, .shx, .dbf to /SHAPEFILE and attempting to open the file, this throws an IOError because the open function is case sensitive and /SHAPEFILE.shp does not exist. Instead of having to re-save the file with a lowercase extension, I think pyshp should support this.

I've created a pull request with a fix:
https://github.com/GeospatialPython/pyshp/pull/116

**Comment by karimbahgat** [comment]
Fixed in #116
