### ISSUE TITLE
Problem with 'C' field and `None` values

### ISSUE THREAD

**Issue by megies** [GeospatialPython/pyshp#123]
See https://github.com/GeospatialPython/pyshp/commit/add32d139eea92a7057d4de3c9976b27394a0e00#commitcomment-25005900

Tests should be really set up as proper unit tests to avoid breaking things..

CC @karimbahgat

**Comment by karimbahgat** [comment]
Good point, removed the strict value error, and added forced string conversion for unknown objects. Also added explicit testing for None, interpreting it as as an empty string "". 
See in 2f3e25752d3301e92ffb07f67a5176ad415742cd. 

Regarding the unittests, I absolutely agree. I won't be able to, but would gladly accept any PR on this. Created a separate issue in #152.
