### ISSUE TITLE
Type Error using shapefile.Writer

### ISSUE THREAD

**Issue by mkatychev** [GeospatialPython/pyshp#129]
Using the latest documentation and the newest version( 1.2.12) I get an issue almost identical to [an earlier one](https://github.com/GeospatialPython/pyshp/issues/100) where I get a TypeError traceback.

```
Traceback (most recent call last):
  File "/Users/indoorgeo/Documents/shptester.py", line 19, in <module>
    w.shape(shaperec.shape)
  File "/Library/Python/2.7/site-packages/shapefile.py", line 1086, in shape
    return self._shapes[i]
TypeError: object cannot be interpreted as an index
```

Here is the code to reproduce it ( I tried to follow the doucmentation as closely as possible):

```
import shapefile

w = shapefile.Writer(shapeType=5)
# create two shapefile records/shape objects
w.field('name', 'C')
w.poly(parts=[[[122,37,4,9], [117,36,3,4]], [[115,32,8,8],
    [118,20,6,4], [113,24]]])
w.record('poly1')
w.poly(parts=[[[123,37,4,9], [112,36,3,4]], [[112,32,8,8],
    [118,20,6,4], [115,24]]])
w.record('poly2')
w.save('/Users/baseuser/Desktop/script_test/test')

r = shapefile.Reader('/Users/baseuser/Desktop/script_test/test')

# create new writer object
w = shapefile.Writer(shapeType=r.shapeType)

# ignore deletion field
w.fields = r.fields[1:]

for shaperec in r.iterShapeRecords():
    w.record(*shaperec.record)
    w.shape(shaperec.shape)

```

any help is appreciated

**Comment by mkatychev** [comment]
turns out the documentation on the landing page did not reference master which is quite confusing

**Comment by mohammedayub44** [comment]
I'm getting the same error. What was the solution for this?

**Comment by mkatychev** [comment]
@mohammedayub44 the documentation references the wrong branch (1.2X) rather than master, quite confusing. Long term I would suggest you move over to fiona (much better documentation case in point) for parsing shapefiles. I think my solution for this was specifying an index like so: ` w.record(*shaperec.record[index])`
