### ISSUE TITLE
How do I concatenate two shapefiles/DBF files

### ISSUE THREAD

**Issue by mohammedayub44** [GeospatialPython/pyshp#137]
I looked through the documentation of this library. I could not find any reference to append or add records to existing shapefiles or concatenate shapefiles. etc. I'm I missing something on the Wiki page?

**Comment by karimbahgat** [comment]
We don't currently have a lot of recipes like that in the documentation, although it might be good to add. [Here's an example from Joel's website](http://geospatialpython.com/2011/02/merging-lots-of-shapefiles-quickly.html) if you're using version <1.2.x.
Or if you're using version 2.x, this should work:
```
w = shapefile.Writer()
w.fields = [] # define fields here, maybe read from first shapefile
for f in filepaths:
    r = shapefile.Reader(f)
    for sr in r.iterShapeRecords():
        w.record(*sr.record)
        w.shape(sr.shape)
```
