### ISSUE TITLE
Polygons not showing in QGIS 2.18

### ISSUE THREAD

**Issue by Olsthoorn** [GeospatialPython/pyshp#149]
Shapefiles with shapeType = shapefile.POLYGON don't show up. Same for shapefiles generated with shapeType =shapefile.POLYLINE. Both in GQGIS 2.18

As it turned out after several hours searching for the cause:

POLYGON shapefile parts have to be writting with shapele.Writer.poly(parts=...)) and
POLYLINE shapefile parts have to be written with shapefile.Writer.line(parts= ... )) 

The documentation says that you're free to choose either line(..) or poly(...) to write the coordinates, and indeed both shapefiles are read by QGIS without complaints, and QGIS knows the extent of the shapfiles, but they don't display unless they are generated by shapefile.Writer by the correct function.

Theo Olsthoorn 180610

**Comment by karimbahgat** [comment]
The two methods are indeed identical, but if you use line() for a Polygon file, the 'shapeType' arg defaults to LineString, and the opposite for poly() on LineString files. If you were on an older version, pyshp wouldn't have noticed that the wrong shapeType was added, but in newer versions it raises an exception. Have removed from the docs to avoid the confusion. 

There have been a few issues arising from having to set the shapeType correctly, which is easy to forget, and there should only be one correct way of doing things. So as of 0c182098e614e9274e638488a19af7a12674b532, you can no longer use any method you like. There is instead a designated method for each shape type, so there is no longer a need for a type argument.
