### ISSUE TITLE
'Writer' object has no attribute 'recNum'

### ISSUE THREAD

**Issue by geniuszxd** [GeospatialPython/pyshp#156]
And also no "shpNum" and "autoBalance" attribute
Are they removed?
1.2.12 with python 3.6

**Comment by karimbahgat** [comment]
Just checked the source code for 1.2.12, and seems .shpNum did not exist back then, and .autobalance was limited to the now extinct Editor class. Both exist in the current 2.0dev version. 
It seems you maybe read the most recent GitHub 2.0dev documentation but were using an older 1.2.12 version? 
Going to the update the pypi version here shortly.

**Comment by karimbahgat** [comment]
v2.0.0 now updated and available on PyPI.
