### ISSUE TITLE
Auto converting setup description to be PyPI readable

### ISSUE THREAD

**Issue by karimbahgat** [GeospatialPython/pyshp#170]
In the past, the PyPI description, contained and extracted from README.md, was manually edited and converted from Markdown to ReStructuredText (since PyPI only renders RST). With the newly overhauled PyPI website, the description cannot be manually edited. Until PyPI gets around to supporting Markdown, we must therefore find a way to automatically do this conversion when defining the 'description' arg in the setup.py script. Not sure what would be best here, but one easy way could be to have the setup.py script automatically convert to RST using the [iPandoc](https://pypi.org/project/iPandoc/) wrapper for the docverter.com online service API. And to only require this for actual deployment.

**Comment by micahcochran** [comment]
> since PyPI only renders RST

[Fairly recently added support for Markdown](https://pypi.org/help/#description-content-type).

**Comment by karimbahgat** [comment]
So they finally added it, great. Oddly enough, the newest released bugfix version 2.0.1 included the recommended content type (see 92f275b65b0efcf3048e92d53fa911575c5f509d), but PyPI still isn't rendering the markdown. Github is rendering it alright, but maybe there's a tiny formatting error that PyPI can't handle.

**Comment by micahcochran** [comment]
[Have you upgraded `setuptools` recently?](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi)  
version 38.6.0 or better is required.

**Comment by karimbahgat** [comment]
That could possibly be it. But deployment to pypi is done automatically via Travis CI, so not sure how that works. I guess that depends what version setuptools Travis uses? Do you know how to check or change that?

**Comment by micahcochran** [comment]
To check the setuptools version in .travis.yml:
`pip list | grep setuptools`

If you want to install a newer version of setuptools in .travis.yml:
`pip install -U setuptools>=38.6.0`

**Comment by karimbahgat** [comment]
Great, thanks! Trying it out for the next release.

**Comment by karimbahgat** [comment]
Looks like it worked, [now rendering correctly on PyPI](https://pypi.org/project/pyshp/2.1.0/). Thanks again!
