### ISSUE TITLE
Error in accessing record content in shapefile.Shaperecord object

### ISSUE THREAD

**Issue by alexandrutarna** [GeospatialPython/pyshp#176]
https://github.com/GeospatialPython/pyshp/blob/85b534c166acddd4e2dc322402fc6f952fd7a1da/shapefile.py#L471
 I am getting an error when I try to access the elements of the record. Even if I just try to view the records in the debugger I get the error shown in the image below. 

![image](https://user-images.githubusercontent.com/34584499/51691348-4704d300-2003-11e9-975f-9af473a272ef.png)

**Comment by karimbahgat** [comment]
Seems like this method didn't account for that in Python 3, calling dict.values() returns a dictvalues iterator rather than a list. Fixed now, plus better autocomplete results.

**Comment by karimbahgat** [comment]
Fixed in version 2.1.0
