### ISSUE TITLE
write records extend yields error

### ISSUE THREAD

**Issue by mshariful** [GeospatialPython/pyshp#183]
Hello,
As I execute the following code
`import shapefile
import utm
r = shapefile.Reader("NYC_MUSEUMS_GEO")

w = shapefile.Writer(str(r.shapeType))

w.fields = list(r.fields)

w.records.extend(r.records())`

the last line of code yields the following error. Any help/suggestion is very much appreciated. Thanks, Sharif

> w.record.extend(r.records())  # READ https://pypi.org/project/pyshp/
Traceback (most recent call last):

  File "<ipython-input-12-7793ebca0e1f>", line 1, in <module>
    w.record.extend(r.records())  # READ https://pypi.org/project/pyshp/

AttributeError: 'function' object has no attribute 'extend'

**Comment by karimbahgat** [comment]
Sorry that this is way too late, but your code would only work for pyshp v1.x, so I would guess you have the newer pyshp v2.x, where records are written one-by-one instead of appended/extended to a list. Do instead:

```
for rec in r.records():
    w.record(*rec)
```
