### ISSUE TITLE
Shapefile error "expected str, bytes or os.PathLike object, not int"

### ISSUE THREAD

**Issue by adrienPAv** [GeospatialPython/pyshp#184]
Hi,

I start programming with Shapefile module and I'm already stuck in the 2nd line.

```
import shapefile as shp
w = shp.Writer(shp.POINT)
```
And I get this error :

```
  File "C:\Users\a.pavoine\AppData\Local\Continuum\anaconda3\lib\ntpath.py", line 202, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int
```

I don't understand why this code doesn't work because it's seem to be the Shapefile programmation's basics.

Thank you.

**Comment by micahcochran** [comment]
Here's a snippet from the pyshp source:
```python
class Writer(object):
    """Provides write support for ESRI Shapefiles."""
    def __init__(self, target=None, shapeType=None, autoBalance=False, **kwargs):
```

The first argument is `target` which should be some kind of filename (with a possible path).  The second argument is `shapeType`, which `shp.POINT` should be vaild.

Therfore, your code should look something like this:
```Python
import shapefile as shp
w = shp.Writer("write_this.shp", shp.POINT)
```

That error message you got is a little cryptic and could be improved.

**Comment by karimbahgat** [comment]
Correct, the original code would have been valid for pyshp v1, but was changed in v2 to accept target filepath as the first arg. Nevertheless, just added a type check on the target arg and more informative error.
