### ISSUE TITLE
signed_area error for coordinates with dimensions > 2

### ISSUE THREAD

**Issue by clement-tourriere** [GeospatialPython/pyshp#185]
signed_area method doesn't support shapes with coordinates containing more than 2 dimensions. 

A simple fix would be to change ligne 163: 
https://github.com/GeospatialPython/pyshp/blob/master/shapefile.py#L163

From 
`xs, ys = map(list, zip(*coords))` to `xs, ys = map(list, zip(*coords))[0:2]`

I can do a PR if you want.

With best regard.

**Comment by karimbahgat** [comment]
Fixed now, but had to tweak it slightly for py3 support. Just out of curiosity, were you using the signed_area function directly or did it happen as part of some other pyshp function?
