### ISSUE TITLE
Fill background color for polygon shapefiles

### ISSUE THREAD

**Issue by Manikandan85** [GeospatialPython/pyshp#189]
Hi,

Thanks for this wonderful module first.

I am working on a python script to create polygon shape files using this module.
I successfully generated .shp files. 
But when I viewed the file through "Google Earth" Map, the polygon area is filled with white color.
![image](https://user-images.githubusercontent.com/3661057/61126434-07a34380-a4ca-11e9-93fa-e19985ec7571.png)
Is there any parameters or options available in the module to set poly area fill color based on our choice.

**Comment by fiveham** [comment]
As far as I know, there is nowhere in the shapefile standard ([link to the definitive whitepaper](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf)) to incorporate style information (such as colors).  As such, there could never be any way in this or any other shapefile-handling module to set a fill color.

If you want to ensure your polygons have appropriate styles in Google Earth, then it might be safer to use BeautifulSoup (bs4) to build a KML document directly.

**Comment by karimbahgat** [comment]
As @fiveham said, this would be a Google Earth issue. Shapefiles only contain coordinates, no styling :)
