### ISSUE TITLE
Why limited the length of field to 10?

### ISSUE THREAD

**Issue by kuno** [GeospatialPython/pyshp#2]
I am new to shapefile, I saw in this line of code
https://github.com/GeospatialPython/pyshp/blob/master/shapefile.py#L744

That you limited the lenght of the field to 10 at most, can you explain why?

**Comment by jinz2014** [comment]
Dear Author,

In the dbf file format https://en.wikipedia.org/wiki/.dbf, the size of the field name is 11 bytes, not 10 bytes. Could it be fixed if it is a bug ?

Database field descriptor bytes

0-10	11 bytes	Field name in ASCII (zero-filled)

Thank you for reading and reply.

**Comment by eldang** [comment]
@jinz2014 [the shapefile article](https://en.wikipedia.org/wiki/Shapefile#Data_storage) spells out that the maximum length of a field name is only 10 characters.  I don't know what the 11th byte is used for, but it's existence doesn't allow shapefiles to have 11 character field names.

It may be possible to hack something that lets people use longer field names within pyshp, but [this stack exchange thread](https://gis.stackexchange.com/questions/15784/how-to-bypass-10-character-limit-of-field-name-in-shapefiles) makes clear why that would be a bad idea.

**Comment by micahcochran** [comment]
In DBF [the 11th byte is a zero (00h) value, for null termination](http://www.clicketyclick.dk/databases/xbase/format/dbf.html#DBF_STRUCT).   It is probably the way to make seem to be somewhat like C null terminated strings.  You might be able to use fscanf to read it in, which almost nobody would do today.  Remember, dBase is a DOS format with design decision made back in the 1980s.

It is not a bug, its a feature! :smile: 

ESRI's ArcGIS software has aliases for field, which I assume is just in the map .MXD file for display to the end user.

**Comment by jinz2014** [comment]
Thank you for your answer.
