### ISSUE TITLE
Mistake in documentation – Shapefiles with elevation (Z) values

### ISSUE THREAD

**Issue by RosBer97** [GeospatialPython/pyshp#201]
There is a mistake in documentation of pyshp, I think. --> "Shapes with elevation (Z) values are added with the following methods: "pointz", "multipointz", "linez", and "polygonz"."

But name of metod for polygons with Z coordinate is not polygonz but polyz, I get this correct information throught (help(shapefile.Writer) in Python console. Mistake is here on Git Hub documentation and also on the web: https://pypi.org/project/pyshp/#3d-and-other-geometry-types

I am newbie in Python and Git, so I am sorry if this is not the best way to report the issue.

**Comment by karimbahgat** [comment]
This was the right way to report it @RosBer97 , appreciate it! Fixed now, and will be included in next version.
