### ISSUE TITLE
assertion error with floats and improving the assertion error message?

### ISSUE THREAD

**Issue by apiszcz** [GeospatialPython/pyshp#21]
I am encountering an assertion error when I write floats with a lot of precision. Decreasing the precision solves the issue, again, this may be 'my' specification for the field. So this is probably not a bug, but it might be useful to have the assertion print out the field name and value for developers?

        w.field('test','N',16,3)

This value was causing the issue:
'test': 0.77569341788591528,

When rounded no error
round(val,4)

ERROR fragment

  File "c:\p\via\lib\shapefile.py", line 1043, in save
    self.saveDbf(target)
  File "c:\p\via\lib\shapefile.py", line 1015, in saveDbf
    self.__dbfRecords()
  File "c:\p\via\lib\shapefile.py", line 902, in __dbfRecords
    assert len(value) == size
AssertionError

**Comment by karimbahgat** [comment]
All asserts have been changed to more useful exceptions.
