### ISSUE TITLE
Error while reading a shapefile

### ISSUE THREAD

**Issue by adimpflmoser** [GeospatialPython/pyshp#214]
Hello everybody,

I'm just busy trying to read and write shapefiles using PyShp 2.13. which fails right away.

The following code

`import shapefile

objShapeReader = shapefile.Reader("C:/Daten/Gis-Data/BadFuessing/ESRIShapefile/AX_Gebaeude")

objRec = objShapeReader.records()
print(len(objRec))`

produces the following output:

`Traceback (most recent call last):
  File "C:\Daten\NASImportOgr\shapetest.py", line 5, in <module>
    objRec = objShapeReader.records()
  File "C:\Program Files\Python39\lib\site-packages\shapefile.py", line 1306, in records
    r = self.__record(oid=i)
  File "C:\Program Files\Python39\lib\site-packages\shapefile.py", line 1281, in __record
    value = u(value, self.encoding, self.encodingErrors)
  File "C:\Program Files\Python39\lib\site-packages\shapefile.py", line 104, in u
    return v.decode(encoding, encodingErrors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 9: invalid continuation byte`

The shapefile is converted from a German xml-file using ogr2org

Can anybody shed some light on this?

**Comment by karimbahgat** [comment]
This looks like the shapefile has a non-standard non-utf8 encoding. Unless you know the file's encoding, I would suggest trying the latin encoding: `objShapeReader = shapefile.Reader("C:/Daten/Gis-Data/BadFuessing/ESRIShapefile/AX_Gebaeude", encoding='latin')`. Or if you can't figure out which encoding was used, just ignore the encoding errors: `objShapeReader = shapefile.Reader("C:/Daten/Gis-Data/BadFuessing/ESRIShapefile/AX_Gebaeude", encodingErrors='ignore')`. See https://github.com/GeospatialPython/pyshp#unicode-and-shapefile-encodings for more details.
