### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [GeospatialPython/pyshp#218]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine README.md and observe `similiarly`, however expect to see `similarly`.
- Examine shapefile.py and observe `appropritate`, however expect to see `appropriate`.
- Examine shapefile.py and observe `elavation`, however expect to see `elevation`.
- Examine README.md and observe `inspecing`, however expect to see `inspecting`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/pyshp/pull/new/bugfix_typos

Thanks.

**Comment by karimbahgat** [comment]
Thanks, very neat tool!
