### ISSUE TITLE
IS it possible to increase the max size of a shape file

### ISSUE THREAD

**Issue by paalped** [GeospatialPython/pyshp#221]
Hi, I need to merge a couple of large shapefiles, but I come across this error:

raise ShapefileException('The .shp file has reached its file size limit > 4294967294 bytes (4.29 GB). To fix this, break up your
 file into multiple smaller ones.')

line 1556, in __shapefileHeader
    f.write(pack(">i", self.__shpFileLength()))
struct.error: argument out of range

I actually have several smaller ones, but I need to combine them for an analysis.

**Comment by karimbahgat** [comment]
Unfortunately, that's a builtin limitation of the shapefile format. Essentially, the format uses uint32 (which has a maximum value of 4.29 billion) to refer to the byte offset of the file position of each shape. Hence no shape can be referenced beyond the 4.29 billionth byte, or 4.29GB. Any solution would have to divide the data into several files, or use a different file format.
