### ISSUE TITLE
shapefile.Writer issue

### ISSUE THREAD

**Issue by Hydrogeologist** [GeospatialPython/pyshp#224]
shape_writer = shapefile.Writer(shapefile.POLYGON)

above code line throws the following exception and not quite sure how to solve;

Exception: The target filepath 5 must be of type str/unicode, not <class 'int'>.

**Comment by karimbahgat** [comment]
It appears you are using the old v1 API for creating a Writer, but this has changed in v2. If you look at the [latest docs](https://github.com/GeospatialPython/pyshp#the-writer-class), the first arg to the Writer class is the file path to write to. To also [set the shape type](https://github.com/GeospatialPython/pyshp#setting-the-shape-type), you just add the `shapeType` kwarg. So your example would be: 

`shape_writer = shapefile.Writer('shapefile.shp', shapeType=shapefile.POLYGON)`
