### ISSUE TITLE
Expected a three-dimensional coordinate (x,y,z) but only got the first two (x,y).

### ISSUE THREAD

**Issue by haobo-autra** [GeospatialPython/pyshp#236]
Hey,here is my shpfile data in json format. 
![image](https://user-images.githubusercontent.com/98007234/155674924-5cb70224-6b96-4161-bf2a-c0bdeb20e4a8.png)
But in my teminal I can only get the (x,y) coordinate
![image](https://user-images.githubusercontent.com/98007234/155676265-cee43f78-0d70-43ef-9bab-58cb324f0d8f.png)
Here is my usage.
![image](https://user-images.githubusercontent.com/98007234/155676124-12f9ec22-71de-433d-aa2a-5e8de35c42aa.png)
Is there any one can tell me why, what's wrong with the code.
Thanks.

**Comment by haobo-autra** [comment]
Oh, I got it. I can use shape(0).z to get the z coordinate!
`        if nPoints:
            flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
            record.points = list(izip(*(iter(flat),) * 2))
        # Read z extremes and values
        if shapeType in (13,15,18,31):
            (zmin, zmax) = unpack("<2d", f.read(16))
            record.z = _Array('d', unpack("<%sd" % nPoints, f.read(nPoints * 8)))`

**Comment by haobo-autra** [comment]
Oh, I got it. I can use shape(0).z to get the z coordinate!
![image](https://user-images.githubusercontent.com/98007234/155679385-413113df-e182-4d65-8557-2dd18b56be62.png)

**Comment by karimbahgat** [comment]
Glad you were able to find the solution. Documentation for handling 3d and elevation shapefiles can be found in the readme: https://github.com/GeospatialPython/pyshp#3d-and-other-geometry-types. I hope to add more useful 3d examples in the future.

**Comment by haobo-autra** [comment]
Thanks for your patient explanation!  
I get it.
