### ISSUE TITLE
Writing to only one shapefile type throwing an error

### ISSUE THREAD

**Issue by mem00** [GeospatialPython/pyshp#237]
`w = shapefile.Writer(shp="/path/tofile.shp")`

as per the documentation

>>> w = shapefile.Writer(dbf='shapefiles/test/onlydbf.dbf')
>>> w.field('field1', 'C')

throws 

`ShapefileException: No file-like object available.`

when trying to write a polygon 

`w.poly(geometry)`

**Comment by karimbahgat** [comment]
I was able to reproduce your error. We did have unit tests for this usecase that created a writer, but the error only happens when trying to add the first shape which we didn't do in the test. Will get this fixed for the next release.

**Comment by karimbahgat** [comment]
Fixed the error and the tests, should be available in next version. Thanks for finding the issue!
