### ISSUE TITLE
INTEGER VALUE OF 0 stack trace

### ISSUE THREAD

**Issue by apiszcz** [GeospatialPython/pyshp#24]
```
    we.field('frame','N',9,0)
```

If the value in the field is non-zero the write succeeds, if the value is 0 the following stack trace occurs.

raceback (most recent call last):
  File "lib\tc\tc.py", line 2809, in <module>
    run(sys.argv[1])
  File "lib\tc\tc.py", line 1666, in run
    td,kd=shape_to_tripdct(src,cfg)
  File "lib\tc\tc.py", line 1747, in shape_to_tripdct
    attributes = sf.records()
  File "C:\p\tc_64\lib\shapefile.py", line 535, in records
    r = self.__record()
  File "C:\p\tc_64\lib\shapefile.py", line 500, in __record
    value = int(value)
ValueError: invalid literal for int() with base 10: '0.0'
Press any key to continue . . .

**Comment by karimbahgat** [comment]
There have been several data type updates, so this is likely to have been fixed by now. I also tested to write a file with that field definition, adding both a non-zero and a zero value. Saving and reading it back worked correctly.

**Comment by karimbahgat** [comment]
Here is the test code:

```
import shapefile

w = shapefile.Writer()
w.field('frame','N',9,0)
w.record(1)
w.record(0)
w.save("testframe.shp")

r = shapefile.Reader("testframe.shp")
print r.records()
```
