### ISSUE TITLE
Spelling Errors in README

### ISSUE THREAD

**Issue by RossGammon** [GeospatialPython/pyshp#26]
During a quality review of the last upload of pyshp in Debian, the following spelling errors were identified:
$ codespell --quiet-level=3
...
./README.txt:265: dicussed  ==> discussed
./README.txt:490: seperate  ==> separate
./README.txt:551: nmae  ==> name

I would have gladly produced a Pull Request for such a minor fix, but the same errors occur in PKG-INFO, README.pdf & README.html. Assuming one of them is the master, how were the other files produced from it.

It would be great if only one of these files was distributed in the tarball, and the rest built from the master file at build time. Is that possible?

**Comment by karimbahgat** [comment]
Fixed in 0cc0d58e9278f61a111d62a4e6231ae417bf37e3.
No longer any .pdf or .html files, all docs in README.md.
