### ISSUE TITLE
_shapes.extend access

### ISSUE THREAD

**Issue by apiszcz** [GeospatialPython/pyshp#29]
PyCharm code inspection is flagging using the subject method as an issue.
Access to a protected member _shapes of a class less... (Ctrl+F1) 
This inspection warns if a protected member is access outside the class or a descendant of the class where it's defined.
Is there a better way to do this concatenate?
Can this method be made public?
                    r=shapefile.Reader(f)
                    w.records.extend(r.records())
                    w._shapes.extend(r.shapes())

**Comment by GeospatialPython** [comment]
Yes - all of the private methods should be made public.
