### ISSUE TITLE
UnboundLocalError when writing large shp file (while calculating shpFileLength)

### ISSUE THREAD

**Issue by djvdorp** [GeospatialPython/pyshp#3]
Thanks for the great pySHP library! However, I'm currently facing an error, I hope you can help me out? It happens when I try to write a pretty large shp file, I tried with another file before and that worked just fine. 

I have already read your suggestions here:
http://geospatialpython.com/2011/02/merging-lots-of-shapefiles-quickly.html

And I also already Google'd around to see if an solution was around, but I couldn't find one myself. I can provide you with the testdata files, as they are Creative Commons, and I also can provide you with a sample of the code I'm using.

I am using the latest pyshp version from pypi (1.2.1) on Python 2.7.6 (OS X 10.9.2).

``` python
Traceback (most recent call last):
  File "/Users/daniel/Projects/shapefileimport/app.py", line 55, in <module>
    hectopunten_output_writer.saveShp("Wegvakken")
  File "/Users/daniel/.virtualenvs/shapefileimport/lib/python2.7/site-packages/shapefile.py", line 995, in saveShp
    self.__shapefileHeader(self.shp, headerType='shp')
  File "/Users/daniel/.virtualenvs/shapefileimport/lib/python2.7/site-packages/shapefile.py", line 709, in __shapefileHeader
    f.write(pack(">i", self.__shpFileLength()))
  File "/Users/daniel/.virtualenvs/shapefileimport/lib/python2.7/site-packages/shapefile.py", line 617, in __shpFileLength
    size += nParts * 4
UnboundLocalError: local variable 'nParts' referenced before assignment
```

**Comment by karimbahgat** [comment]
From the code, the only reason nParts wouldn't be referenced is that the writer._shapes list contained an object without a "parts" attribute. But all ._shapes objects should be a _Shape object and all _Shape objects have a .parts attribute. So I suspect this was caused by user code that tried adding non-_Shape objects onto the Writer.

**Comment by aitahtman** [comment]
Hey @djvdorp 
@karimbahgat is right. you should check your  shapes list there is necessary one or many non _Shape objects.
