### ISSUE TITLE
How do I specify an integer attribute?

### ISSUE THREAD

**Issue by apiszcz** [GeospatialPython/pyshp#34]
w.field('testattr', 'N')

This appears to create a double, with length 50, precision 0.

I was wondering what I need to specify to obtain an integer attribute.

Python 3.4.3 and shapefile.py 1.2.3

**Comment by riggsd** [comment]
```python
    def field(self, name, fieldType="C", size="50", decimal=0):
```

Numeric values in a .DBF file aren't stored as binary, they're stored as the character representation; so the `size` parameter is really a "character width" when serializing the value. 

So if by "integer attribute" you mean a signed 16-bit integer (for example), the "widest" value you'd need to be able to store is `−32767`, which has a width of 6 characters. So you'd define the field as:

```python
w.field('testattr', 'N', 6, 0)  # 16-bit int
```

A 32-bit long integer would need to store values as wide as `−2147483647`, or 11 characters:

```python
w.field('testattr', 'N', 11, 0)  # 32-bit long int
```

That said, there's nothing wrong with creating a numeric field too wide other than wasted space, so your default width of 50 characters should work fine for integer values.

**Comment by karimbahgat** [comment]
As a sidenote, the dbf format does allow integer fields stored as actual integers instead of as strings, but this is not yet implemented. And it seems most shapefiles store integers via the "N" field set to 0 decimals.

**Comment by griguolcomerranas** [comment]
From what I can see in my tests with the library and QGIS, the length of the field defines the type. Assuming the decimals are set to 0, if the field length is 9 or less it is considered an integer, if the length is between 10 and 18 it is considered a long integer (integer64), and any length higher than 18 is considered a double (real) number.
