### ISSUE TITLE
DBF only

### ISSUE THREAD

**Issue by AlainFELER** [GeospatialPython/pyshp#35]
The class Reader comment says "If one of the three files (.shp, .shx, .dbf) is missing no exception is thrown until you try to call a method that depends on that particular file." but if the .shp AND the .shx are missing it throws an exception.
It would be nice if the library accepted to open a .dbf alone : of course a shp with no .shp and no .shx is a poor one, but shapefile would still be very useful to analyse fields, compare dbfs, and some other things. Other libraries like dbf do that, but they have their own problems (no "introspection" with dbf for example).

**Comment by flother** [comment]
Good news: you _can_ use pyshp to read a DBF file only. When you instantiate a `Reader` object, pass in a file-like object using the `dbf` argument but don't pass in a shapefile:

```python
import shapefile

sf = shapefile.Reader(dbf=open("example.dbf", "rb"))
for record in sf.iterRecords():
    pass
```

**Comment by karimbahgat** [comment]
Agree that the implementation did not fully live up to the docs. As @flother pointed out, this was only implemented when passing file-like objects. cb7f1240170d4b8ef6d6f386492bc616b3b8a519 implements the same flexibility for filepaths, including to read standalone dbf files.
