### ISSUE TITLE
How to validate shapefiles?

### ISSUE THREAD

**Issue by sellonen** [GeospatialPython/pyshp#37]
I find pyshp really valuable, thanks for your work. However, sometimes it creates shapfiles that I'm unable to open in certain GIS programs, namely MapInfo. The same files normally open just fine in qGIS. As MapInfo gives absolutely no information about what went wrong, I don't know where to start debugging, even though I'd be happy to contribute to pyshp.

Do you have any recommendation about how to diagnose the shapefiles?

**Comment by micahcochran** [comment]
Are you able to do anything with misbehaving shapefiles with GDAL?  Specifically `ogrinfo` or `ogr2ogr`.  

With `ogr2ogr` (or QGIS) you might be able to convert these shapefile to a [MapInfo format](http://www.gdal.org/drv_mitab.html).

I can see how Shapefile can have some odd things in it that might makes some programs break.  They have cause me some grief.

It would be nice if there was some kind of tool that ensures that the file conforms to the shapefile spec.   If it runs in ESRI ArcGIS software, it is up to to the ESRI spec.

Another idea might be to send data to MapInfo to have them investigate what went wrong.

**Comment by sellonen** [comment]
The problem is exactly that all GDAL tools handle the files generated using pyshp just fine. However, even if I use ogr2ogr to convert from shp to mapinfo, the resulting file won't open in MapInfo. It is entirely possible that the bug is in MapInfo instead of GDAL or pyshp.

I just wanted to ask if you knew about shapefile verification tools, but apparently they do not exist. Which, I must say, is very weird for such a widely used format.
