### ISSUE TITLE
PyPI package: LICENSE.TXT missing

### ISSUE THREAD

**Issue by petrrr** [GeospatialPython/pyshp#38]
It looks like the `LICENSE.TXT` (and maybe some other file which should have made it to the tarball, e.g. `changelog`) is missing. I am referring to version 1.2.3. This makes it a bit difficult to comply with the license. Maybe this could be added again.

**Comment by nchammas** [comment]
To be clear, there *is* a LICENSE file [in the repo](https://github.com/GeospatialPython/pyshp/blob/master/LICENSE.TXT) (MIT), but I'm guessing it didn't get packaged for the upload to PyPI.

**Comment by sebastic** [comment]
This issue should be fixed now that the change from #64 is merged, the next PyPI distribution should contain the LICENSE.TXT and changelog.txt again.

**Comment by karimbahgat** [comment]
Fixed now that new version is up on pypi.
