### ISSUE TITLE
Python 3: make decoding shapefile fields more lenient...

### ISSUE THREAD

**Issue by micahcochran** [GeospatialPython/pyshp#41]
This was reported https://github.com/matplotlib/basemap/issues/187 and subsequently merged into basemap.  ~~I have a basemap PR that deletes the inline copy of pyshp and makes pyshp an external dependency.~~  I just want to make sure that this patch has its chance for the "mainline" pyshp.

Edit: pyshp is now an external dependency in the development version of matplotlib/basemap.

**Comment by karimbahgat** [comment]
House-cleaning: All encoding-related issues and PRs have been collected in and can be referenced from #74.
