### ISSUE TITLE
Read only speficied lat/long and plot on the basemap.

### ISSUE THREAD

**Issue by wxguy** [GeospatialPython/pyshp#45]
I hope you are aware that your `pyshp` module is the backbone of `readshapefile` function from `basemap` (matplotlib sub module). I am trying to plot some data on a basemap and using one of the NE (world) shapefile for plotting boundary. For some reason the `readshapefile` function only able to read entire shapefile instead of reading the lat/long specified in the basemap instance. This reading of shapefile takes tooo much time which eventually delays the plotting time. 

I have not found any solution for the problem of slow reading shpaefiles. I have raised this issue in the  `matplotlib` issue (later on it was moved to `basemap` issue tracker). The relevent issue raised is here https://github.com/matplotlib/basemap/issues/263 .

It would be great if you can solve this issue (either read the shapefile faster or read only the data within specified lat/long) at your end and I am sure that developers behind the matplotlib/basemap will integrate it later.

**Comment by GeospatialPython** [comment]
Wow! No - I had no idea it was used in matplotlib.  The goal of PyShp is to be lightweight, pure Python, and dependency free.  Once you've committed to compiling, installing, configuring C libraries as matplotlib does, you might as well go all the way and use OGR and Fiona/Shapely.  If the baseman toolkit used OGR instead, it would open up a whole world of possibilities beyond shapefiles to include geodatabases for starters. 

PyShp might one day implement spatial indexing for faster reading, but to do so in pure Python will require a significant amount of work.

To solve your immediate problem, you can just bypass the readshapefile method and use OGR yourself.  There are several examples of using it with marplotlib:

http://ondrejintheair.blogspot.com/2011/11/plot-polygon-shapefiles-using-ogr-and.html

http://sensitivecities.com/so-youd-like-to-make-a-map-using-python-EN.html#.VsHcE8ehjdk

http://www.trondkristiansen.com/?page_id=1267

http://geoexamples.blogspot.com/2014/10/basemap-raster-clipping-with-shapefile.html

https://github.com/matplotlib/basemap/blob/master/examples/testgdal.py

[](http://www2.geog.ucl.ac.uk/~plewis/geogg122/_build/html/Chapter4_GDAL/OGR_Python.html)

If I can help in any way let me know.

**Comment by wxguy** [comment]
Sorry to comment on the closed issue. 

Just to plot the boundary lines why do we required to install complected modules. I wont be using not even shape fill. I am sure that your package might do this already (just extracting the shape values within the specified lat/lon) or you might be having an idea to implement that. 

I had trouble with Basemap reading as well and overcame by using pickling (storing the `basemap` instance on hard disk) and reading it back. That way the plotting time reduced drastically from next time onwards for the same lat/lon. Why don’t the same method cant be applied for the shape file as well? Is it possible to create a new shape file for a specific lat/log and store it on hard disk and each time if same lat/lon is called the speed will improve greatly? This is not the solution but consider it as trick for time being.

The examples you have linked to is really new to me. I will take some time to understand. 

Please forgive my ignorance if I have asked too much or simple thing repeatedly.  It is just because I am new to `shape` world. But could not find any documentation for my specific problem.
