### ISSUE TITLE
Add encoding='' kwarg to shapefile.Reader and shapefile.Writer

### ISSUE THREAD

**Issue by jtbraun** [GeospatialPython/pyshp#46]
The natural earth data stores its strings encoded as Windows-1252 (versions < 3.x) or UTF-8 (>= 3.x). Currently, shapefile.py tries to guess at what it should do in the b() and u() routines.  For Python-3, utf-8 is assumed as the encoding, and for python-2, no encode or decode operations are performed.

It's my opinion that the user should be able to specify the encoding for the DBF fields as a kwarg to Reader and Writer.  If provided, b() should use that instead of utf-8 for the v.encode() operation, and it should do so for both python 2 and python 3.  Likewise, u(v) should be modified to decode in a similar manner.

This would enable cartopy (a popular mapping module with built-in support for natural earth data) to provide the encoding parameter, returning "accurate" data to the user, regardless of natural earth data version or python version.

**Comment by jtbraun** [comment]
See related but https://github.com/SciTools/cartopy/issues/739

**Comment by ArtiiP** [comment]
i make somhing like this in  https://github.com/ArtiiP/pyshp/commit/df95b5feb40ac8d95bf2aa818b831e075bc82f7f
but i only tested this on py3, and code is old

**Comment by micahcochran** [comment]
I've kinda been wondering why pyshp doesn't support the [shapefile .CPG file format](https://en.wikipedia.org/wiki/Shapefile#Overview) for specifying the DBF file's codepage.

GDAL reads the .cpg file in the [dbfopen.c driver](https://github.com/OSGeo/gdal/blob/trunk/gdal/ogr/ogrsf_frmts/shape/dbfopen.c) and stores its contents verbatim in the `psDBF->pszCodePage`.  Then, it translated it using [ConvertCodePage()](https://github.com/OSGeo/gdal/blob/8f4a9197084c543cde9ce534cc63f83d03fe6a2c/gdal/ogr/ogrsf_frmts/shape/ogrshapelayer.cpp#L279).  

Perhaps one issue is the [Python standard encoding](https://docs.python.org/3/library/codecs.html#standard-encodings) aren't always the same names.   

I also think that an `encoding` parameter for Reader/Writer, as suggest, would also be a good approach.

**Comment by jtbraun** [comment]
Oh! I didn't realize that the .cpg file was actually part of ESRI's standard. That's interesting.  If so, then pyshp should probably natively support looking for, opening and interpreting the .cpg file automatically, just as it does with the .dbf file today.

**Comment by micahcochran** [comment]
I did a little searching for .cpg and ESRI and found files [date back to 2003](https://www.google.com/search?q=.cpg+esri&safe=active&espv=2&biw=1371&bih=682&source=lnt&tbs=cdr%3A1%2Ccd_min%3A%2Ccd_max%3A2003&tbm=).  Also, [ArcGIS Desktop 9.3 from 2008 has a mention of .cpg](http://webhelp.esri.com/arcgisdesktop/9.3/index.cfm?TopicName=Shapefile_file_extensions).  It seems like ESRI's software atleast supports .cpg files, but I isn't  spelled out in the ESRI shapefile standard from 1998.

**Comment by ArtiiP** [comment]
i sync my code
This is not ideal, because standard DBF expected field names only in ASCII, and it is not currently checked.

Support for cpg will be nice (but propably better create new issue for this)

**Comment by micahcochran** [comment]
One more thing about codepages, just for completeness.  The DBF format has a byte  (0x1d from the top) in the header that stores the [language driver ID](http://www.clicketyclick.dk/databases/xbase/format/dbf.html#DBF_NOTE_5_SOURCE).   The .cpg file supports this legacy by having and code that begins with "LDID/" followed by the same bytes as the language driver ID.

I've written some code to do some of this based on mapserver's dbfopen.c code.  Next, I need to get some test cases to make sure that it seems to work.

**Comment by karimbahgat** [comment]
House-cleaning: All encoding-related issues and PRs have been collected in and can be referenced from #74.
