### ISSUE TITLE
README.md not included

### ISSUE THREAD

**Issue by jdhughes-usgs** [GeospatialPython/pyshp#65]
README.md is not included in the pyshp 1.2.8 distribution on PyPI.

**Comment by tacaswell** [comment]
This causes `pip install pyshp` to fail https://travis-ci.org/matplotlib/matplotlib/jobs/153746028

**Comment by tacaswell** [comment]
This appears to be fixed by 39fbd440c25bea6c2785e0347460aea5b4c51ec4 .

Duplicate of #63

**Comment by karimbahgat** [comment]
New version 1.2.10 uploaded to pypi, fixing the pip install issue, also solving matplotlib/matplotlib#6962.
