### ISSUE TITLE
Python MemeoryError exception on larage shapefile

### ISSUE THREAD

**Issue by mawg** [GeospatialPython/pyshp#72]
[Update] please ignor/deletee this. I was running a 32 bit versoin of Python, which can only address 2gB of RAM.

--------------------------------------------------------------------------------

I am new to Pyshp (but not to Python) and am staring big by getting my dataset from http://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/downloads/GMTED/GMTED_Metadata/GMTED2010_Spatial_Metadata.zip

It unpacks to 1.7gB, with the .shp file being 1.2gB.

With this code:

import shapefile
data = shapefile.Reader("data_file.shp")

instantiating the Shapefile reader gives me an exception MemoryError when using Pyshp.  But I am using ony 3% of my machine's 32gB, so I don't understand it.

Is there any other approach that I can take? Can process the file in chunks in Python? Or use some tool to spilt the file into chinks, then process each of them individually?

**Comment by GeospatialPython** [comment]
I'll leave it so people can see how you solved it if they have the same issue.  Could you post the answer affirmatively on GIS StackExchange too?

**Comment by mawg** [comment]
Pardon me for being dumb.  Do you want me to post a question there and answer it? I already have one on S.O, at  http://stackoverflow.com/questions/39639579/memory-error-on-large-shapefile-in-python/39639735#39639735, but not on GIS StackExchange

**Comment by karimbahgat** [comment]
Pyshp shouldn't need 2GB of memory to load any shapefile @mawg. I saw from your SO post that you used the `shapes()` method which loads all 1.2GB of shapes into memory at once. There is another `iterShapes()` method which is much more memory friendly and should fix your problem. See my answer on SO: http://stackoverflow.com/a/39649506/2898490
